var courses = [
    {'category': 'all',          'course' : 110, isUpper: false, 'description': 'Technical Graphics'},
    {'category': 'all',          'course' : 135, isUpper: false, 'description': 'Graphic Communications'},
    {'category': 'all',          'course' : 210, isUpper: false, 'description': 'Creative Thinking and Design Visualizatio'},
    {'category': 'all',          'course' : 211, isUpper: false, 'description': 'Introduction to Video Game Art'},
    {'category': 'animation',    'course' : 211, isUpper: false, 'description': 'Introduction to Video Game Art'},
    {'category': 'all',          'course' : 215, isUpper: false, 'description': 'Introduction to Graphics Programming'},
    {'category': 'all',          'course' : 230, isUpper: false, 'description': 'Digital Illustration in Publishing'},
    {'category': 'all',          'course' : 237, isUpper: false, 'description': 'Web Content Desig'},
    {'category': 'all',          'course' : 295, isUpper: false, 'description': 'Introduction to Technical Imaging'},
    {'category': 'pv',           'course' : 295, isUpper: false, 'description': 'Introduction to Technical Imaging'},
    {'category': 'all',          'course' : 303, isUpper: true, 'description': 'Digital Publishin'},
    {'category': 'all',          'course' : 312, isUpper: true, 'description': '3-D Computer Graphics Modeling and Representatio'},
    {'category': 'all',          'course' : 314, isUpper: true, 'description': 'Multimedia Design, Planning and Storyboards'},
    {'category': 'all',          'course' : 333, isUpper: true, 'description': 'Printing Technology'},
    {'category': 'all',          'course' : 334, isUpper: true, 'description': 'Image Capture and Manipulation'},
    {'category': 'all',          'course' : 335, isUpper: true, 'description': 'Computer Systems Technology'},
    {'category': 'all',          'course' : 340, isUpper: true, 'description': 'Information Design and Usabilit'},
    {'category': 'all',          'course' : 384, isUpper: true, 'description': 'Commercial Photograph'},
    {'category': 'all',          'course' : 394, isUpper: true, 'description': 'Special Topic'},
    {'category': 'all',          'course' : 402, isUpper: true, 'description': 'New Media Internet Technologie'},
    {'category': 'all',          'course' : 411, isUpper: true, 'description': 'Computer Animatio'},
    {'category': 'all',          'course' : 413, isUpper: true, 'description': 'Professional Portfolio Design and Presentatio'},
    {'category': 'all',          'course' : 414, isUpper: true, 'description': 'Web Site Design and Internet/Web Technologies'},
    {'category': 'all',          'course' : 417, isUpper: true, 'description': 'Advanced Internet Programming'},
    {'category': 'all',          'course' : 418, isUpper: true, 'description': 'Multimedia Authoring, Scripting and Production'},
    {'category': 'all',          'course' : 432, isUpper: true, 'description': 'Graphic Industry Business Practice'},
    {'category': 'all',          'course' : 435, isUpper: true, 'description': 'Web Management and E-Commerce'},
    {'category': 'all',          'course' : 437, isUpper: true, 'description': 'Color Reproduction Systems'},
    {'category': 'all',          'course' : 450, isUpper: true, 'description': 'Digital Workflow in Graphic Industries'},
    {'category': 'all',          'course' : 490, isUpper: true, 'description': 'Advanced Commercial Photography'},
    {'category': 'all',          'course' : 494, isUpper: true, 'description': 'Digital Publishing Semina'},
    {'category': 'all',          'course' : 494, isUpper: true, 'description': 'Special Topic'},
    {'category': 'ddpp',         'course' : 333, isUpper: true, 'description': 'Printing Technology'},
    {'category': 'ddpp',         'course' : 334, isUpper: true, 'description': 'Image Capture and Manipulation'},
    {'category': 'ddpp',         'course' : 437, isUpper: true, 'description': 'Color Reproduction Systems'},
    {'category': 'ddpp',         'course' : 450, isUpper: true, 'description': 'Digital Workflow in Graphic Industries'},
    {'category': 'ddpp',         'course' : 494, isUpper: true, 'description': 'Digital Publishing Seminar'},
    {'category': 'animation',    'course' : 312, isUpper: true, 'description': '3-D Computer Graphics Modeling and Representation'},
    {'category': 'animation',    'course' : 334, isUpper: true, 'description': 'Image Capture and Manipulation'},
    {'category': 'animation',    'course' : 411, isUpper: true, 'description': 'Computer Animation'},
    {'category': 'pv',           'course' : 334, isUpper: true, 'description': 'Image Capture and Manipulation'},
    {'category': 'pv',           'course' : 394, isUpper: true, 'description': 'Advanced Video Techniques'},
    {'category': 'pv',           'course' : 394, isUpper: true, 'description': 'Special Topics'},
    {'category': 'pv',           'course' : 494, isUpper: true, 'description': 'Special Topics'},
    {'category': 'pv',           'course' : 490, isUpper: true, 'description': 'Advanced Commercial Photography'},
    {'category': 'dd',           'course' : 340, isUpper: true, 'description': 'Information Design and Usability'},
    {'category': 'dd',           'course' : 402, isUpper: true, 'description': 'New Media Internet Technologies'},
    {'category': 'dd',           'course' : 414, isUpper: true, 'description': 'Web Site Design and Internet/Web Technologies'},
    {'category': 'dd',           'course' : 417, isUpper: true, 'description': 'Advanced Web Markup and Scripting'},
    {'category': 'dd',           'course' : 418, isUpper: true, 'description': 'Multimedia Authoring, Scripting and Production'},
    {'category': 'dd',           'course' : 435, isUpper: true, 'description': 'Website and E-Commerce Strategie'}
]